name: "Build Docker image"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

jobs:
  build_ubuntu_docker_image:
    strategy:
      fail-fast: false
      matrix:
          base_image_name: [ubuntu]
          base_image_tag: [bionic, focal, jammy]
    name: "${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}"
    # always use latest linux worker, as it should not have any impact
    # when it comes to building docker images.
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: publish image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        containerRegistry: true
        buildArgs: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
            VCS_REF=${{ github.sha }}
            IGN_DISTRO=none
        imageName: "ign-${{ matrix.base_image_name }}"
        tag: "${{ matrix.base_image_tag }}"

  build_ubuntu_docker_image_ign:
    strategy:
      fail-fast: false
      matrix:
          base_image_name: [ubuntu]
          ign_distro: [citadel, fortress, garden]
          include:

          - ign_distro: citadel 
            base_image_tag: bionic 

          - ign_distro: fortress 
            base_image_tag: focal 

          - ign_distro: garden 
            base_image_tag: focal

          - ign_distro: garden 
            base_image_tag: jammy 

    name: "${{ matrix.base_image_name }}-${{ matrix.ign_distro }}-${{ matrix.base_image_tag }}"
    # always use latest linux worker, as it should not have any impact
    # when it comes to building docker images.
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: publish image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        containerRegistry: true
        buildArgs: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
            VCS_REF=${{ github.sha }}
            IGN_DISTRO=${{ matrix.ign_distro }}
        imageName: "ign-${{ matrix.base_image_name }}"
        tag: "${{ matrix.ign_distro }}-${{ matrix.base_image_tag }}"
