name: "Build Docker image"
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

jobs:
  build_ubuntu_docker_image:
    strategy:
      fail-fast: false
      matrix:
          base_image_name: [ubuntu]
          base_image_tag: [bionic, focal, jammy]
    name: "${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}"
    # always use latest linux worker, as it should not have any impact
    # when it comes to building docker images.
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: publish image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        containerRegistry: true
        buildArgs: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
            VCS_REF=${{ github.sha }}
            GZ_DISTRO=none
        imageName: "gz-${{ matrix.base_image_name }}"
        tag: "${{ matrix.base_image_tag }}"

  build_ubuntu_docker_image_gz:
    strategy:
      fail-fast: false
      matrix:
          base_image_name: [ubuntu]
          build_name: [citadel-bionic, fortress-bionic, fortress-focal, garden-focal, garden-jammy]
          include:
          - build_name: citadel-bionic
            gz_distro: citadel
            base_image_tag: bionic
          - build_name: fortress-bionic
            gz_distro: fortress
            base_image_tag: bionic
          - build_name: fortress-focal
            gz_distro: fortress
            base_image_tag: focal
          - build_name: garden-focal
            gz_distro: garden
            base_image_tag: focal
          - build_name: garden-jammy
            gz_distro: garden
            base_image_tag: jammy
    name: "${{ matrix.base_image_name }}-${{ matrix.gz_distro }}-${{ matrix.base_image_tag }}"
    # always use latest linux worker, as it should not have any impact
    # when it comes to building docker images.
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: publish image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        containerRegistry: true
        buildArgs: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
            VCS_REF=${{ github.sha }}
            GZ_DISTRO=${{ matrix.gz_distro }}
        imageName: "gz-${{ matrix.base_image_name }}"
        tag: "${{ matrix.gz_distro }}-${{ matrix.base_image_tag }}"
