name: "Build Docker image"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

jobs:
  build_ubuntu_docker_image:
    strategy:
      fail-fast: false
      matrix:
          base_image_name: [ubuntu]
          base_image_tag: [bionic, focal]
    name: "${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}"
    # always use latest linux worker, as it should not have any impact
    # when it comes to building docker images.
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: publish image
      uses: matootie/github-docker@v2.2.2
      with:
        accessToken: ${{ secrets.github_token }}
        buildArg: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
            VCS_REF=${{ github.sha }}
            IGN_DISTRO=none
        imageName: "setup-ign-docker-${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}"
    # Publish the image to DockerHub too
    - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - run: docker images
    - run: "docker tag docker.pkg.github.com/ros-tooling/setup-ros-docker/setup-ros-docker-${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}:master rostooling/setup-ros-docker:${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}-latest"
      if: github.event_name != 'pull_request'
    - run: "docker push rostooling/setup-ros-docker:${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}-latest"
      if: github.event_name != 'pull_request'

  build_ubuntu_docker_image_ros:
    strategy:
      fail-fast: false
      matrix:
          base_image_name: [ubuntu]
          ign_distro: [citadel, dome, edifice]
          include:

          - ign_distro: citadel 
            base_image_tag: bionic 
            output_image_tag: ubuntu-bionic-ign-citadel

          - ign_distro: dome
            base_image_tag: bionic 
            output_image_tag: ubuntu-bionic-ign-dome

          - ign_distro: dome
            base_image_tag: focal
            output_image_tag: ubuntu-focal-ign-dome

          - ign_distro: edifice
            base_image_tag: focal
            output_image_tag: ubuntu-focal-ign-edifice

    name: "${{ matrix.output_image_tag }}"
    # always use latest linux worker, as it should not have any impact
    # when it comes to building docker images.
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: publish image
      uses: matootie/github-docker@v2.2.2
      with:
        accessToken: ${{ secrets.github_token }}
        buildArg: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
            EXTRA_APT_PACKAGES=ros-${{ matrix.ros_distro }}-${{ matrix.ros_variant }}
            VCS_REF=${{ github.sha }}
            IGN_DISTRO=${{ matrix.ign_distro }}
        imageName: "setup-ign-docker-${{ matrix.output_image_tag }}"
    # Publish the image to DockerHub too
    - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - run: docker images
    - run: "docker tag docker.pkg.github.com/ros-tooling/setup-ros-docker/setup-ros-docker-${{ matrix.output_image_tag }}:master rostooling/setup-ros-docker:${{ matrix.output_image_tag }}-latest"
      if: github.event_name != 'pull_request'
    - run: "docker push rostooling/setup-ros-docker:${{ matrix.output_image_tag }}-latest"
      if: github.event_name != 'pull_request'
